---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: elk
    run_list:
      - recipe[elk::elasticsearch]
      - recipe[elk::logstash]
      - recipe[elk::kibana]
    attributes:
